packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@pixiv/three-vrm": ^3.4.3
  "@cloudflare/workers-types": ^4.20260503.1
  "@orpc/client": ^1.14.0
  "@orpc/contract": ^1.14.0
  "@orpc/server": ^1.14.0
  "@types/three": ^0.181.0
  "@types/node": ^24
  "@vitejs/plugin-vue": ^6.0.6
  element-plus: ^2.13.7
  hono: ^4.12.16
  pinia: ^3.0.4
  three: ^0.181.1
  typescript: ^6.0.3
  unplugin-auto-import: ^21.0.0
  unplugin-vue-components: ^32.0.0
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.20
  vite-plus: ^0.1.20
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue: ^3.5.33
  vue-router: ^5.0.6
  vue-tsc: ^3.2.7
  wrangler: ^4.87.0
  zod: ^4.4.2

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
