export const SPEC_VERSION = "1.0" as const;

export const REQUIRED_HUMAN_BONES = [
  "hips",
  "spine",
  "head",
  "leftUpperLeg",
  "leftLowerLeg",
  "leftFoot",
  "rightUpperLeg",
  "rightLowerLeg",
  "rightFoot",
  "leftUpperArm",
  "leftLowerArm",
  "leftHand",
  "rightUpperArm",
  "rightLowerArm",
  "rightHand",
] as const;

export const OPTIONAL_HUMAN_BONES = [
  "chest",
  "upperChest",
  "neck",
  "jaw",
  "leftToes",
  "rightToes",
  "leftShoulder",
  "rightShoulder",
  "leftThumbMetacarpal",
  "leftThumbProximal",
  "leftThumbDistal",
  "leftIndexProximal",
  "leftIndexIntermediate",
  "leftIndexDistal",
  "leftMiddleProximal",
  "leftMiddleIntermediate",
  "leftMiddleDistal",
  "leftRingProximal",
  "leftRingIntermediate",
  "leftRingDistal",
  "leftLittleProximal",
  "leftLittleIntermediate",
  "leftLittleDistal",
  "rightThumbMetacarpal",
  "rightThumbProximal",
  "rightThumbDistal",
  "rightIndexProximal",
  "rightIndexIntermediate",
  "rightIndexDistal",
  "rightMiddleProximal",
  "rightMiddleIntermediate",
  "rightMiddleDistal",
  "rightRingProximal",
  "rightRingIntermediate",
  "rightRingDistal",
  "rightLittleProximal",
  "rightLittleIntermediate",
  "rightLittleDistal",
] as const;

export const HUMAN_BONE_NAMES = [...REQUIRED_HUMAN_BONES, ...OPTIONAL_HUMAN_BONES] as const;

export const HUMAN_BONE_LABELS_JA: Record<(typeof HUMAN_BONE_NAMES)[number], string> = {
  chest: "胸",
  head: "頭",
  hips: "腰",
  jaw: "顎",
  leftFoot: "左足首",
  leftHand: "左手",
  leftIndexDistal: "左人差し指 先",
  leftIndexIntermediate: "左人差し指 中",
  leftIndexProximal: "左人差し指 付け根",
  leftLittleDistal: "左小指 先",
  leftLittleIntermediate: "左小指 中",
  leftLittleProximal: "左小指 付け根",
  leftLowerArm: "左前腕",
  leftLowerLeg: "左すね",
  leftMiddleDistal: "左中指 先",
  leftMiddleIntermediate: "左中指 中",
  leftMiddleProximal: "左中指 付け根",
  leftRingDistal: "左薬指 先",
  leftRingIntermediate: "左薬指 中",
  leftRingProximal: "左薬指 付け根",
  leftShoulder: "左肩",
  leftThumbDistal: "左親指 先",
  leftThumbMetacarpal: "左親指 根元",
  leftThumbProximal: "左親指 付け根",
  leftToes: "左つま先",
  leftUpperArm: "左上腕",
  leftUpperLeg: "左太もも",
  neck: "首",
  rightFoot: "右足首",
  rightHand: "右手",
  rightIndexDistal: "右人差し指 先",
  rightIndexIntermediate: "右人差し指 中",
  rightIndexProximal: "右人差し指 付け根",
  rightLittleDistal: "右小指 先",
  rightLittleIntermediate: "右小指 中",
  rightLittleProximal: "右小指 付け根",
  rightLowerArm: "右前腕",
  rightLowerLeg: "右すね",
  rightMiddleDistal: "右中指 先",
  rightMiddleIntermediate: "右中指 中",
  rightMiddleProximal: "右中指 付け根",
  rightRingDistal: "右薬指 先",
  rightRingIntermediate: "右薬指 中",
  rightRingProximal: "右薬指 付け根",
  rightShoulder: "右肩",
  rightThumbDistal: "右親指 先",
  rightThumbMetacarpal: "右親指 根元",
  rightThumbProximal: "右親指 付け根",
  rightToes: "右つま先",
  rightUpperArm: "右上腕",
  rightUpperLeg: "右太もも",
  spine: "背骨",
  upperChest: "上胸",
};

export function getHumanBoneLabelJa(bone: (typeof HUMAN_BONE_NAMES)[number]) {
  return HUMAN_BONE_LABELS_JA[bone];
}

export const PRESET_EXPRESSION_NAMES = [
  "happy",
  "angry",
  "sad",
  "relaxed",
  "surprised",
  "aa",
  "ih",
  "ou",
  "ee",
  "oh",
  "blink",
  "blinkLeft",
  "blinkRight",
  "neutral",
] as const;

export const FORBIDDEN_EXPRESSION_PRESETS = [
  "lookUp",
  "lookDown",
  "lookLeft",
  "lookRight",
] as const;

export const BONE_PARENT_MAP: Partial<
  Record<(typeof HUMAN_BONE_NAMES)[number], (typeof HUMAN_BONE_NAMES)[number]>
> = {
  spine: "hips",
  chest: "spine",
  upperChest: "chest",
  neck: "upperChest",
  head: "neck",
  jaw: "head",
  leftUpperLeg: "hips",
  leftLowerLeg: "leftUpperLeg",
  leftFoot: "leftLowerLeg",
  leftToes: "leftFoot",
  rightUpperLeg: "hips",
  rightLowerLeg: "rightUpperLeg",
  rightFoot: "rightLowerLeg",
  rightToes: "rightFoot",
  leftShoulder: "upperChest",
  leftUpperArm: "leftShoulder",
  leftLowerArm: "leftUpperArm",
  leftHand: "leftLowerArm",
  rightShoulder: "upperChest",
  rightUpperArm: "rightShoulder",
  rightLowerArm: "rightUpperArm",
  rightHand: "rightLowerArm",
  leftThumbMetacarpal: "leftHand",
  leftThumbProximal: "leftThumbMetacarpal",
  leftThumbDistal: "leftThumbProximal",
  leftIndexProximal: "leftHand",
  leftIndexIntermediate: "leftIndexProximal",
  leftIndexDistal: "leftIndexIntermediate",
  leftMiddleProximal: "leftHand",
  leftMiddleIntermediate: "leftMiddleProximal",
  leftMiddleDistal: "leftMiddleIntermediate",
  leftRingProximal: "leftHand",
  leftRingIntermediate: "leftRingProximal",
  leftRingDistal: "leftRingIntermediate",
  leftLittleProximal: "leftHand",
  leftLittleIntermediate: "leftLittleProximal",
  leftLittleDistal: "leftLittleIntermediate",
  rightThumbMetacarpal: "rightHand",
  rightThumbProximal: "rightThumbMetacarpal",
  rightThumbDistal: "rightThumbProximal",
  rightIndexProximal: "rightHand",
  rightIndexIntermediate: "rightIndexProximal",
  rightIndexDistal: "rightIndexIntermediate",
  rightMiddleProximal: "rightHand",
  rightMiddleIntermediate: "rightMiddleProximal",
  rightMiddleDistal: "rightMiddleIntermediate",
  rightRingProximal: "rightHand",
  rightRingIntermediate: "rightRingProximal",
  rightRingDistal: "rightRingIntermediate",
  rightLittleProximal: "rightHand",
  rightLittleIntermediate: "rightLittleProximal",
  rightLittleDistal: "rightLittleIntermediate",
};

export const REST_TRANSLATIONS: Partial<
  Record<(typeof HUMAN_BONE_NAMES)[number], [number, number, number]>
> = {
  hips: [0, 1, 0],
  spine: [0, 0.18, 0],
  chest: [0, 0.16, 0],
  upperChest: [0, 0.12, 0],
  neck: [0, 0.1, 0],
  head: [0, 0.14, 0],
  jaw: [0, -0.04, 0.04],
  leftUpperLeg: [0.12, -0.22, 0],
  leftLowerLeg: [0, -0.32, 0],
  leftFoot: [0, -0.3, 0.05],
  leftToes: [0, -0.04, 0.08],
  rightUpperLeg: [-0.12, -0.22, 0],
  rightLowerLeg: [0, -0.32, 0],
  rightFoot: [0, -0.3, 0.05],
  rightToes: [0, -0.04, 0.08],
  leftShoulder: [0.11, 0.06, 0],
  leftUpperArm: [0.14, 0, 0],
  leftLowerArm: [0.22, 0, 0],
  leftHand: [0.22, 0, 0],
  rightShoulder: [-0.11, 0.06, 0],
  rightUpperArm: [-0.14, 0, 0],
  rightLowerArm: [-0.22, 0, 0],
  rightHand: [-0.22, 0, 0],
};

export const LOOK_AT_DEFAULT_OFFSET: [number, number, number] = [0, 0.06, 0];
export const DEFAULT_DURATION_SECONDS = 2;
