/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimationGeneratorPanel: typeof import('./src/components/editor/AnimationGeneratorPanel.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExportPanel: typeof import('./src/components/editor/ExportPanel.vue')['default']
    FileImportPanel: typeof import('./src/components/editor/FileImportPanel.vue')['default']
    KeyframeInspector: typeof import('./src/components/editor/KeyframeInspector.vue')['default']
    PlaybackPanel: typeof import('./src/components/editor/PlaybackPanel.vue')['default']
    PreviewViewport: typeof import('./src/components/editor/PreviewViewport.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimelinePanel: typeof import('./src/components/editor/TimelinePanel.vue')['default']
    TrackList: typeof import('./src/components/editor/TrackList.vue')['default']
    ValidationPanel: typeof import('./src/components/editor/ValidationPanel.vue')['default']
  }
}
